# express the vector (3,7,-7) as a linear combination of the vectors(1,2,3) an(2,3,7)and(3,5,6).

In [3]:
#input
from numpy import*
target_vector=array([3,7,-4])
v1=array([1,2,3])
v2=array([2,3,7])
v3=array([3,5,6])
A=column_stack((v1,v2,v3))
coefficients=linalg.solve(A,target_vector)
a,b,c=coefficients.round()
print(target_vector,"=",a,v1,"+",b,v2,"+",c,v3)

[ 3  7 -4] = 2.0 [1 2 3] + -4.0 [2 3 7] + 3.0 [3 5 6]


# express the vector (1,7,-4) as a linear combination of the vector(1,-3,2),(2,-1,1) and (1,2,3).

In [4]:
#input
from numpy import*
target_vector=array([1,7,-4])
v1=array([1,-3,2])
v2=array([2,-1,1])
v3=array([1,2,3])
A=column_stack((v1,v2,v3))
coefficients=linalg.solve(A,target_vector)
a,b,c=coefficients.round()
print(target_vector,"=",a,v1,"+",b,v2,"+",c,v3)

[ 1  7 -4] = -3.0 [ 1 -3  2] + 2.0 [ 2 -1  1] + -0.0 [1 2 3]


# express the vector (4,-1,8) as a linear combination of the vector(1,-3,2),([1,2,-1) and (5,4,-2).

In [5]:
#input
from numpy import*
target_vector=array([4,-1,8])
v1=array([1,-3,2])
v2=array([1,2,-1])
v3=array([5,4,-2])
A=column_stack((v1,v2,v3))
coefficients=linalg.solve(A,target_vector)
a,b,c=coefficients.round()
print(target_vector,"=",a,v1,"+",b,v2,"+",c,v3)

[ 4 -1  8] = 15.0 [ 1 -3  2] + 44.0 [ 1  2 -1] + -11.0 [ 5  4 -2]


## express the vector (1,-2,5) as a linear combination of the vector(1,1,1),(1,2,3) and (2,-1,1).

In [1]:
#input
from numpy import*
target_vector=array([1,-2,5])
v1=array([1,1,1])
v2=array([1,2,3])
v3=array([2,-1,1])
A=column_stack((v1,v2,v3))
coefficients=linalg.solve(A,target_vector)
a,b,c=coefficients.round()
print(target_vector,"=",a,v1,"+",b,v2,"+",c,v3)

[ 1 -2  5] = -6.0 [1 1 1] + 3.0 [1 2 3] + 2.0 [ 2 -1  1]


# express the vector (3,-7,4) as a linear combination of the vector(1,3,1),(1,-5,3) and (2,-1,7).

In [7]:
#input
from numpy import*
target_vector=array([3,-7,4])
v1=array([1,3,1])
v2=array([1,-5,3])
v3=array([2,-1,7])
A=column_stack((v1,v2,v3))
coefficients=linalg.solve(A,target_vector)
a,b,c=coefficients.round()
print(target_vector,"=",a,v1,"+",b,v2,"+",c,v3)

[ 3 -7  4] = 2.0 [1 3 1] + 3.0 [ 1 -5  3] + -1.0 [ 2 -1  7]
