# [q1]  if a= i+2j+3k,b=2i+3j+4k,evaluate 
i)a+b
ii)a-b
iii)3a
iv)5a+6b
v)7a-8b
vi)a.b
vii)axb
 viii)[a]
 ix)unit vector of a
 

In [2]:
import numpy as np
v1=np.asarray([1,2,3])
v2=np.asarray([2,3,4])
sum=v1+v2
print(sum)

[3 5 7]


In [2]:
subtract=v1-v2
print(subtract)

[-1 -1 -1]


In [5]:
multi=3*v1
print(multi)

[3 6 9]


In [8]:
value1=(5*v1)+(6*v2)
print(value1)

[17 28 39]


In [9]:
value2=7*v1-8*v2
print(value2)

[ -9 -10 -11]


In [10]:
np.dot(v1,v2)

20

In [11]:
np.cross(v1,v2)

array([-1,  2, -1])

In [14]:
import numpy as np
v1=np.asarray([1,2,3])
import math
mv1=math.sqrt(v1[0]**2+v1[1]**2+v1[2]**2)
print(mv1)

3.7416573867739413


In [15]:
unitvect=v1/mv1
print(unitvect)

[0.26726124 0.53452248 0.80178373]


# If underline a = 3i + 5j + 2k , b = 5i + 8j + 7k evaluate
(i) a+b 
(ii)a-b
(iii) 7a
(iv) 4a + 7b
(v)6a-2b 
(vi) a.b
(vii) aXb
(viii) |a|
(ix) unit vector of a.

In [3]:
import numpy as np
v1=np.asarray([3,5,2])
v2=np.asarray([5,8,7])
sum=v1+v2
subtract=v1-v2
multi=7*v1
value1=4*v1+7*v2
value2=6*v1-2*v2


mv1=math.sqrt(v1[0]**2+v1[1]**2+v1[2]**2)
unitvect=v1/mv1


print(sum)
print(subtract)
print(multi)
print(value1)
print(value2)
print(mv1)
print(unitvect)

NameError: name 'math' is not defined

In [21]:
np.dot(v1,v2)


69

In [20]:
np.cross(v1,v2)

array([ 19, -11,  -1])

# 2. If underline a = 2i + 9j + 3k , b = 7i + 5j + 2k evaluate
(i) a+b
(ii)a-b
(iii) 8a
(iv) 3a + 9b
(v)7a-2b 
(vi) a.b
(vii) aXb
(viii) | a |
(ix) unit vector of a.

In [22]:
import numpy as np
v1=np.asarray([2,9,3])
v2=np.asarray([7,5,2])
sum=v1+v2
subtract=v1-v2
multi=8*v1
value1=3*v1+9*v2
value2=7*v1-2*v2


mv1=math.sqrt(v1[0]**2+v1[1]**2+v1[2]**2)
unitvect=v1/mv1


print(sum)
print(subtract)
print(multi)
print(value1)
print(value2)
print(mv1)
print(unitvect)

[ 9 14  5]
[-5  4  1]
[16 72 24]
[69 72 27]
[ 0 53 17]
9.695359714832659
[0.20628425 0.92827912 0.30942637]


In [23]:
np.dot(v1,v2)

65

In [24]:
np.cross(v1,v2)

array([  3,  17, -53])

# If underline a = 4i + 7j + 5k , b = 3i + 8j + 5k evaluate
(i) a + b
(ii)a-b
(iii) 9a
(iv) 5a + 2b
(v)5a-3b
(vi) a.b
(vii) aXb
(viii) | a |
(ix) unit vector of a.

In [25]:
import numpy as np
v1=np.asarray([4,7,5])
v2=np.asarray([3,8,5])
sum=v1+v2
subtract=v1-v2
multi=9*v1
value1=5*v1+2*v2
value2=5*v1-3*v2


mv1=math.sqrt(v1[0]**2+v1[1]**2+v1[2]**2)
unitvect=v1/mv1


print(sum)
print(subtract)
print(multi)
print(value1)
print(value2)
print(mv1)
print(unitvect)

[ 7 15 10]
[ 1 -1  0]
[36 63 45]
[26 51 35]
[11 11 10]
9.486832980505138
[0.42163702 0.73786479 0.52704628]


In [26]:
np.dot(v1,v2)


93

In [27]:
np.cross(v1,v2)

array([-5, -5, 11])